### ISSUE TITLE
Processing y3-wfd and dr4-v1

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#111]
y3 data set transferred to CC only has 2781 visits. @villarrealas will confirm that indeed there are about 6mths simulated with the wrong PSF, and thus discarded here.
Starting calexp production of y3

**Comment by katrinheitmann** [comment]
Sorry, can you explain this more? There is a problem with the half of the Y3 data? Or am I mis-reading something below? If really half of Y3 is incorrect, when was that found? How did that happen?

On 6/20/19 4:18 PM, Johann Cohen-Tanugi wrote:

y3 data set transferred to CC only has 2781 visits. @villarrealas<https://github.com/villarrealas> will confirm that indeed there are about 6mths simulated with the wrong PSF, and thus discarded here.
Starting calexp production of y3

**Comment by johannct** [comment]
Expectnig @villarrealas to provide confirmation here

**Comment by villarrealas** [comment]
@johannct @katrinheitmann I can verify from my end the following information:

Y3 has a total of 3904 WFD visits - this is a LITTLE smaller than other years already [by comparison, Y5 had 4515 visits], so this means that we've processed ~71% of Y3-wfd from scratch on this run. All other visits were processed in the old PSF model and we had actively chosen to avoid reprocessing anything with a sensor-visit processed for the old PSF model. That choice was primarily due to the fact that the old PSF model might still be useful to process at some point and thus it would be more valuable to have entirely new data (at least this is my understanding).

I believe that all that happened is that Y3 is a little smaller in terms of number of visits AND since we processed Y1-Y3 all at the same time and the sampling was not guaranteed to be ordered or uniform in my simulation, we just happened to have a larger chunk of Y3 run on the old model. Couple that with the fact that I fixed my bug that was causing us to resimulate things we had intended to not come back to and that gives us the effect that we see.

If we really need to come back and resim these missing chunks of a year, we certainly can once we have more allocation, but I imagine that this is not high priority over full new years of WFD or DDF.

**Comment by johannct** [comment]
> Y3 has a total of 3904 WFD visits -
the rest is DDF?

**Comment by johannct** [comment]
Problem is that we start diverging from the actual depth of 3 years etc.... so at some point we will have to renormalize everything

**Comment by johannct** [comment]
Currently I have 9271 ingested visits for y1,y2, and y3. So it is effectively <~2 years right? Can you check how many WFD visits are planned for the other years?

**Comment by johannct** [comment]
@heather999 @airnandez : calexps for y3 are ready

**Comment by johannct** [comment]
249 FATAL reported in the calexp logs for y3 (so at most 249 visits have one FATAL)
[y3-fatal.txt](https://github.com/LSSTDESC/ImageProcessingPipelines/files/3319762/y3-fatal.txt)
- 105 skyCorr failures with the msg `lsst::pex::exceptions::InvalidParameterError: 'Number of columns of design matrix (1) must be smaller than number of data points (0)'`
- 130 CModel failures : `Unable to measure aperture correction for required algorithm 'modelfit_CModel`
- 7 astrometric failures : `TaskError: Fit failed: median scatter on sky ... > 10.000 config.maxScatterArcsec`
- 6 failures with `RuntimeError: No matches to use for photocal`
- 1 failure with `RuntimeError: Unable to match sources`

**Comment by johannct** [comment]
So we are losing 249-105=144 sensors for coadd. It is a very small number, but I wonder if the code should not default to a more robust photometric fit if CModel fails, so as not to completely lose the sensors. @rearmstr ?

**Comment by johannct** [comment]
Launching DR4 : 9271 visits to coadd, 173 target tracts (3 more than dr1b : 2723, 2724 and 2897). Switched to 3 patch per job instead of 5.
![footprint_2 1_alltracts](https://user-images.githubusercontent.com/586081/60080177-a80a1180-972f-11e9-86b6-0b306b6b5e26.png)

**Comment by johannct** [comment]
There are maximul 173*49=8477 patches,  compared to 2522*3=7566 effectively overlapping a sensor.

**Comment by johannct** [comment]
SRS recovered well from the SPS crash at CC, and the production is back full speed since this morning CET.

**Comment by johannct** [comment]
dr4-v1 processing completed. @airnandez requesting transfer of the following directories under `/sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1/` : `dpdd/calexp-v1:coadd-dr4-v1/` and `coadd-dr4-v1*`

**Comment by johannct** [comment]
aborted with the discovery of the AGN issue
