### ISSUE TITLE
Sort out issue setting devtoolset-6 in jobs submitted via SRS from IN2P3

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#19]
Using more recent versions of the DMstack require devtoolset-6.  Setting the compiler in the loadLSST.bash script is failing.
Discussion ongoing on Slack:
https://lsstc.slack.com/archives/C8WSC8QVB/p1519066284000285

**Comment by nicolaschotard** [comment]
This problem was coming from the presence, before the activation of `devtools-6`, of the following line in the batch script sourcing the DM setup:

`set -e # exit on error`

Placing this line right after sourcing the DM setup file containing the line activating `devtools-6` solved the problem. The modification has been made in this [script](https://github.com/LSSTDESC/ReprocessingTaskForce/commit/00eeda11aae3c8d64b782682ea4b72fe42458275#diff-d7e77032e91c3b7f60d005557b6d110aR10>).

In more detail, the `loadLSST.bach` script (e.g. `/sps/lsst/software/lsst_distrib/w_2018_07/loadLSST.bash`) is activating `devtools-6` with

`source scl_source enable devtoolset-6`

`scl_source` is at some point calling `scl_enabled` which exits with an `exit 1` status if `devtools-6` in not activated yet, which if the case when it's called. This exit status is interpreted has an error by the pipeline, which made the job ends prematurely.

**Comment by airnandez** [comment]
Great ! So we can consider this fixed.

**Comment by nicolaschotard** [comment]
Yes. I will leave the issue open a little longer to allow for comments before closing it.

**Comment by johannct** [comment]
should we remove `set -e` alltogether? It seems that on this occurrence the pipeline exits with not clear enough comments for debugging, so at least in the current situation of development it might be better to have another means of flagging error occurrence

**Comment by heather999** [comment]
While we're cleaning up @johannct - can we close this one?

**Comment by johannct** [comment]
this bit us as well on another instance with ingestDriver.... Removing set -e everywhere possible :)

**Comment by nicolaschotard** [comment]
I removed all the `set -e` that I've found already.

**Comment by heather999** [comment]
Also got bit by this at NERSC :)  Making sure DC2Batch.sh doesn't "set -e" when SITE=NERSC either.
