### ISSUE TITLE
What version of the DM stack should we use?

### ISSUE THREAD

**Issue by nicolaschotard** [LSSTDESC/ImageProcessingPipelines#5]
Discussion on what software need to be use for the DC2-DRP
- what version of the LSST stack (`lsst_distrib`) will we be using? 
- make sure that both version of the stack (+ extra libraries) are the same at NERSC and CC-IN2P3
- do we need `lsst_sims`? If so, explain correctly why and document it
- etc.

**Comment by jchiang87** [comment]
Image processing should not need `lsst_sims`.

**Comment by johannct** [comment]
there are some scripts we have been needing for ingestion, but that may be a transient issue.

**Comment by airnandez** [comment]
My proposal:

- Use the most recent weekly of `lsst_distrib` during the DC development and testing phase. Based on experience during those faces, decide on which weekly version to use at both NERSC and CC-IN2P3 for performing the actual challenge.
- Don't rely on any package not included in `lsst_distrib`. At CC-IN2P3 we install extra packages† (via `conda`)  on top of `lsst_distrib` for convenience to the users, mainly for analysis. We ensure that the installation of those extra packages don't modify any package `lsst_distrib` depends on.

_____________
†: the list of packages we currently install for each weekly can be seen [here](https://github.com/airnandez/lsst-centos7-make/blob/master/condaExtraPackages.txt)

**Comment by heather999** [comment]
I agree in principle that we should not hesitate to move forward with the most recent weekly builds of lsst_distrib, but as @nicolaschotard pointed out during Monday's meeting, not all builds work seamlessly.  That has been my experience as well.  The w_2018_04 build in particular was incorrectly tagged and built for about a week until it was fixed by the DM folks. The desire to be up to date needs to be tempered by the need for some marginal stability in the development of the workflow.                 
I would propose that we maintain a "prod" workflow that uses a recent weekly that we know functions and have a "dev" that is the same workflow but is used to exercise the most recent lsst_distrib. That will allow us to provide feedback to DM to work out any problems quickly and buffer us from problems we encounter.

At NERSC we have a similar installation process, where DM dictates the versions of the python modules it depends on and a limited number of added packages, which do not force an upgrade of any DM-dependent python modules.

While there is no direct dependency on lsst_sims for this portion of the processing, I would plan to ask @danielsf to tag sims against the version of lsst_distrib that is ultimately used for production.

**Comment by airnandez** [comment]
@heather999 Your proposal

> I would propose that we maintain a "prod" workflow that uses a recent weekly that we know functions and have a "dev" that is the same workflow but is used to exercise the most recent lsst_distrib. That will allow us to provide feedback to DM to work out any problems quickly and buffer us from problems we encounter.

sounds perfectly reasonable. By proceeding this way we will have a "certified" weekly which is known to work. At some point we will need a mechanism for certifying that a more recent weekly works also.

**Comment by airnandez** [comment]
I forgot to mention that at CC-IN2P3 we use `lsst_distrib` with Python 3 only. This may be relevant in case we intend to use Python 2 at NERSC. I don't know whether there are discrepancies in the numerical results obtained by running the stack under Python 2 or Python 3. If so, we need to take this into account when cross-checking the results produced by the data reduction tasks executed at both sites.

**Comment by nicolaschotard** [comment]
I am definitely in favor of using (only) Python 3 at both site to make sure that we do not need to worry about problems arising from differences in Python version.

**Comment by heather999** [comment]
@airnandez & @nicolaschotard We are definitely using Python 3 at NERSC.  All recent installations of the stack are set up with Python 3 and we have no intention of using python 2.  No worries there! But good to make that clear.

**Comment by heather999** [comment]
One of the things we learned at last week's SSim meeting was that there are recent performance improvements that should appear in the w_2018_14.  I am planning to move to that version at NERSC this week.  https://lsstc.slack.com/archives/C978LTJGN/p1522958729000369

**Comment by heather999** [comment]
Just a note that we're currently using obs_lsstCam + w_2018_30
I have poked NERSC about providing access the /cvmfs DMstack area and am hoping we might make use of it.

**Comment by heather999** [comment]
Recent Run1.2p/i processing is using obs_lsst + w_2018_39

**Comment by heather999** [comment]
Closing as we will track Run2.1i versions in other issues
